---
kind: pipeline
name: Pipeline

steps:
  - name: lint
    image: imrtfm/archlinux:latest
    commands:
      - pacman -Sy --noconfirm python-pylint shellcheck yamllint
      - ./lint-shellcheck.sh
      - ./lint-yamllint.sh
