---
kind: pipeline
name: Pipeline

steps:
  - name: lint
    image: archlinux/base:latest
    commands:
      - pacman -Sy --noconfirm shellcheck yamllint
      - ./lint-shellcheck.sh
      - ./lint-yamllint.sh